CREATE DATABASE SUBE
GO
USE SUBE
GO
SET DATEFORMAT dmy;
GO
CREATE TABLE PROVINCIAS(
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(50)
)
GO
CREATE TABLE LOCALIDADES(
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    IDPROVINCIA INT NOT NULL FOREIGN KEY REFERENCES PROVINCIAS(ID),
    NOMBRE VARCHAR(255)
)
GO
CREATE TABLE DOMICILIOS(
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    IDLOCALIDAD INT NOT NULL FOREIGN KEY REFERENCES LOCALIDADES(ID),
    DIRECCION VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(15) NULL
)
GO
CREATE TABLE USUARIOS(
  ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  APELLIDO VARCHAR(50) NOT NULL,
  NOMBRE VARCHAR(50) NOT NULL,
  DNI VARCHAR(10) NOT NULL UNIQUE,
  IDDOMICILIO INT NOT NULL FOREIGN KEY REFERENCES DOMICILIOS(ID),
  FECHA_NACIMIENTO SMALLDATETIME NOT NULL CHECK ( FECHA_NACIMIENTO >= '1900' AND FECHA_NACIMIENTO <= getdate() ),
  ESTADO BIT NOT NULL DEFAULT(1)
)
GO
CREATE TABLE TARJETAS(
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    FECHAALTA SMALLDATETIME NOT NULL CHECK ( FECHAALTA <= getdate() ),
    IDUSUARIO INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID),
    ESTADO BIT NOT NULL DEFAULT(1)
)
GO
CREATE TABLE MOVIMIENTOS_TARJETAS(
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    FECHA SMALLDATETIME NOT NULL CHECK ( FECHA <= getdate() ),
    IDTARJETA INT NOT NULL FOREIGN KEY REFERENCES TARJETAS(ID),
    IMPORTE MONEY NOT NULL CHECK ( IMPORTE > 0 ),
    TIPOMOVIMIENTO CHAR(1) NOT NULL CHECK ( TIPOMOVIMIENTO IN ('C','D') )
)
GO
CREATE TABLE LINEAS_COLECTIVO(
    COD VARCHAR(5) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,    
    IDDOMICILIO INT NOT NULL FOREIGN KEY REFERENCES DOMICILIOS(ID)
)
GO
CREATE TABLE VIAJES(
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    INTERNO SMALLINT NOT NULL CHECK ( INTERNO > 0 ),
    IDMOVIMIENTOTARJETA INT NOT NULL FOREIGN KEY REFERENCES MOVIMIENTOS_TARJETAS(ID),
    CODLINEACOLECTIVO VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES LINEAS_COLECTIVO(COD)    
)

