
SET DATEFORMAT dmy;
DBCC CHECKIDENT ('MOVIMIENTOS_TARJETAS', RESEED,0) 

INSERT INTO PROVINCIAS (NOMBRE) VALUES('BUENOS AIRES');
INSERT INTO PROVINCIAS (NOMBRE) VALUES('CORDOBA');
INSERT INTO PROVINCIAS (NOMBRE) VALUES('SANTA FE');

INSERT INTO LOCALIDADES (IDPROVINCIA, NOMBRE) VALUES(1, 'SAN MARTIN');
INSERT INTO LOCALIDADES (IDPROVINCIA, NOMBRE) VALUES(1, 'CABA');
INSERT INTO LOCALIDADES (IDPROVINCIA, NOMBRE) VALUES(1, 'MUNRO');
INSERT INTO LOCALIDADES (IDPROVINCIA, NOMBRE) VALUES(1, 'TIGRE');
INSERT INTO LOCALIDADES (IDPROVINCIA, NOMBRE) VALUES(1, 'LANUS');

INSERT INTO DOMICILIOS (IDLOCALIDAD, DIRECCION, TELEFONO) VALUES(1, 'AV. TRIUNVIRATO 3357', '15123578');
INSERT INTO DOMICILIOS (IDLOCALIDAD, DIRECCION, TELEFONO) VALUES(2, 'AV. BELGRANO 465', '01148253697');
INSERT INTO DOMICILIOS (IDLOCALIDAD, DIRECCION, TELEFONO) VALUES(1, 'AV. MARQUEZ 4125', '0118571286');
INSERT INTO DOMICILIOS (IDLOCALIDAD, DIRECCION, TELEFONO) VALUES(2, 'AV. NAZCA 3884', '0112478112');

INSERT INTO USUARIOS (APELLIDO, NOMBRE, DNI, IDDOMICILIO, FECHA_NACIMIENTO, ESTADO) VALUES('GINES', 'SEBASTIAN', '32692718', 1, '13-01-1987', 1);
INSERT INTO USUARIOS (APELLIDO, NOMBRE, DNI, IDDOMICILIO, FECHA_NACIMIENTO, ESTADO) VALUES('GONCALVES', 'CAMILA', '41258732', 2, '01-07-1997', 1);

INSERT INTO LINEAS_COLECTIVO (COD, NOMBRE, IDDOMICILIO) VALUES('328A', 'COOPERATIVA 328', 3);
INSERT INTO LINEAS_COLECTIVO (COD, NOMBRE, IDDOMICILIO) VALUES('328B', 'COOPERATIVA 328', 3);
INSERT INTO LINEAS_COLECTIVO (COD, NOMBRE, IDDOMICILIO) VALUES('110A', 'COOPERATIVA 110', 4);

INSERT INTO TARJETAS (FECHAALTA, IDUSUARIO, ESTADO) VALUES('01-08-2020', 1, 1);
INSERT INTO TARJETAS (FECHAALTA, IDUSUARIO, ESTADO) VALUES('11-10-2021', 1, 0);
INSERT INTO TARJETAS (FECHAALTA, IDUSUARIO, ESTADO) VALUES('05-03-2022', 2, 1);
INSERT INTO TARJETAS (FECHAALTA, IDUSUARIO, ESTADO) VALUES('13-04-2022', 2, 1);


INSERT INTO MOVIMIENTOS_TARJETAS (FECHA, IDTARJETA, IMPORTE, TIPOMOVIMIENTO) VALUES('05-01-2022 08:00:00', 1, 200, 'C');
INSERT INTO MOVIMIENTOS_TARJETAS (FECHA, IDTARJETA, IMPORTE, TIPOMOVIMIENTO) VALUES('05-01-2022 08:05:00', 1, 25, 'D');
INSERT INTO MOVIMIENTOS_TARJETAS (FECHA, IDTARJETA, IMPORTE, TIPOMOVIMIENTO) VALUES('06-01-2022 08:10:00', 1, 25, 'D');
INSERT INTO MOVIMIENTOS_TARJETAS (FECHA, IDTARJETA, IMPORTE, TIPOMOVIMIENTO) VALUES('07-01-2022 08:01:00', 1, 18, 'D');
INSERT INTO MOVIMIENTOS_TARJETAS (FECHA, IDTARJETA, IMPORTE, TIPOMOVIMIENTO) VALUES('07-01-2022 17:10:00', 1, 18, 'D');
INSERT INTO MOVIMIENTOS_TARJETAS (FECHA, IDTARJETA, IMPORTE, TIPOMOVIMIENTO) VALUES('09-01-2022 18:10:00', 1, 25, 'D');


INSERT INTO VIAJES (INTERNO, IDMOVIMIENTOTARJETA, CODLINEACOLECTIVO) VALUES(25, 2, '328A');
INSERT INTO VIAJES (INTERNO, IDMOVIMIENTOTARJETA, CODLINEACOLECTIVO) VALUES(22, 3, '328A');
INSERT INTO VIAJES (INTERNO, IDMOVIMIENTOTARJETA, CODLINEACOLECTIVO) VALUES(4, 4, '328B');
INSERT INTO VIAJES (INTERNO, IDMOVIMIENTOTARJETA, CODLINEACOLECTIVO) VALUES(88, 5, '110A');
INSERT INTO VIAJES (INTERNO, IDMOVIMIENTOTARJETA, CODLINEACOLECTIVO) VALUES(13, 6, '110A');
