CREATE VIEW VW_DATOSUSUARIOS_TARJETAS AS 
SELECT APELLIDO, NOMBRE, ID, ESTADO, SUM(IMPORTES) AS SALDO
FROM (
    SELECT U.APELLIDO, U.NOMBRE, T.ID, T.ESTADO, 
        CASE  MT.TIPOMOVIMIENTO 
            WHEN 'C' THEN MT.IMPORTE
            ELSE (MT.IMPORTE*-1)
        END AS IMPORTES
    FROM USUARIOS U
    INNER JOIN TARJETAS T ON T.IDUSUARIO = U.ID
    INNER JOIN MOVIMIENTOS_TARJETAS MT ON MT.IDTARJETA = T.ID
) DATOSUSUARIO
GROUP BY APELLIDO, NOMBRE, ID, ESTADO

GO
CREATE VIEW VW_DATOSUSUARIOS_VIAJES AS  
    SELECT U.APELLIDO, U.NOMBRE, T.ID, MT.FECHA, MT.IMPORTE, V.INTERNO, L.NOMBRE AS LINEA FROM USUARIOS U
    INNER JOIN TARJETAS T ON T.IDUSUARIO = U.ID
    INNER JOIN MOVIMIENTOS_TARJETAS MT ON MT.IDTARJETA = T.ID
    INNER JOIN VIAJES V ON V.IDMOVIMIENTOTARJETA = MT.ID
    INNER JOIN LINEAS_COLECTIVO L ON L.COD = V.CODLINEACOLECTIVO
